version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: air_quality_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: air_quality_monitoring
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana:latest
    container_name: air_quality_dashboard
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - postgres
    networks:
      - monitoring_net

networks:
  monitoring_net:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:
